name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > ~/ec2-key.pem
          chmod 600 ~/ec2-key.pem
          
      - name: Create SSH directory
        run: | 
          mkdir -p ~/.ssh

      - name: Connect to EC2 and Run Commands
        run: |
          ssh -i ~/ec2-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /path/to/your/app
          git pull origin main
          npm install
          pm2 restart all
          EOF
